name: Java CI

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cache: [maven]
        distribution: [temurin]
        java: [17, 21]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: soft@123!@#
          POSTGRES_DB: student_management
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: ${{ matrix.cache }}

      # Build the student-management-backend project
      - name: Build with Maven
        run: ./mvnw clean package -B -V --no-transfer-progress -DskipTests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/student_management
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: soft@123!@#

      # Run unit tests and integration tests
      - name: Test with Maven
        run: ./mvnw verify -B -V --no-transfer-progress
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/student_management
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: soft@123!@#

      # Generate Surefire HTML report
      - name: Generate Surefire HTML reports
        run: ./mvnw site -DskipTests -B -V --no-transfer-progress
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/student_management
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: soft@123!@#

      # Upload tests and reports
      - name: Upload test and coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports-${{ matrix.os }}-${{ matrix.java }}
          path: |
            target/site/surefire-report.html
            target/surefire-reports
